language: go

install:
  - mkdir ~/.bin
  - curl https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz -O hugo.tgz
  - tar xfv hugo.tgz -C .bin
  - rm hugo.tgz .bin/*.md
  - export PATH=$HOME/.bin:$PATH

script:
  - hugo --theme hemmingway2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master
